### ISSUE TITLE
Can Reaqtor be used to create a native LINQ DBMS?

### ISSUE THREAD

**Issue by sam-wheat** [reaqtive/reaqtor#102]
I was very interested to read "A Little History of Reaqtor".  I suspect that many of the talented developers mentioned in that document have pondered how to create what I have asked for below.  I would love hear thoughts from this team on how these ideas might be implemented.  

Just over a year ago I wrote [this post on Reddit](https://old.reddit.com/r/dotnet/comments/f9ijo2/i_want_to_write_c_in_my_dbms/).  I later contacted [Jeremy Likness](https://github.com/JeremyLikness/jeremylikness-blog/issues/1) with the idea.  
 
My requests:

* A DBMS that will parse and execute my LINQ statements without first translating them to a human readable query (such as ANSI-SQL).

* Ability to deploy my business logic in nuget form to DBMS so that all my LINQ statements will run server-side.

Here is my [original post on Reddit](https://old.reddit.com/r/dotnet/comments/f9ijo2/i_want_to_write_c_in_my_dbms/):

I've been thinking a lot about Blazor the last few weeks. I think Blazor is an inflection point for dotnet core because it demonstrates that dotnet core is mature enough to be offered as a replacement for Javascript.

Embracing Blazor creates a big dependency on Microsoft. Microsoft is betting that dotnet core and the dotnet ecosystem are compelling reasons to take that dependency. I think they are right and I would like to see them take dotnet even farther. Just as they have extended dotnet to the browser, so too would I like them to extend dotnet to the dbms. Such a dbms would be another Microsoft dependency but to me that is an easy concession to make. I am already using Entity Framework to abstract away my dependency on SQL, so if my SQL dbms were replaced by one that parsed my linq query natively the only thing I would notice would be the performance improvement.

The driver behind my desire to move dotnet to the dbms is the benefit that comes from writing business logic in statically typed code. The value of this cannot be overstated. I like being able to write reusable code and I like having it checked at compile time instead of in production. Entity Framework assists greatly to this end but at the end of the day it is only lipstick over the so-called object relational impedance mismatch. It does nothing to close the gap. Don't get me wrong I love EF. But no matter how much it does it is still a workaround. I want a solution that reduces or eliminates the mismatch.

The argument that a dotnet dbms is a Microsoft only solution is a valid one. I think it is worth pointing out that if I want my dotnet application to access my SQL database in an object oriented way I have to use a shim like Entity Framework. I think turnabout is fair play. If a Java developer wants to make a call to my dotnet dbms, he should be the one who has to use a shim.

So what do I mean by a native dotnet dbms?

Right now if I write a linq statement like `...where(x => myMethod(x))` it is not going to be executed on the server if myMethod cannot be mapped to a sql function. So I would like to be able to deploy my service layer as a nuget (think stored procs) directly to the dbms. Also, in order for my linq query to execute it has to be translated to a human readable sql statement. I would not care about that sql statement if I could execute ling natively on the server. Translating to sql is slow, inefficient, and it is an enormous technical hurdle. Why not just bypass it and let the server parse the linq statement natively? I would also like to be able to deploy my model (poco entities) to the dbms as a nuget package. I want to be able to utilize all the power and functionality of the dotnet framework in the place I need it most. Exactly how it should work beyond this I won't even pretend to know.

**Comment by HowardvanRooijen** [comment]
Hi Sam,

there are some interesting points here. Some random thoughts:

I'm not sure if Blazor "is the thing" - rather it's the transpilation of .NET to WASM (https://webassembly.org). If you look at what the Microsoft/DeisLabs folk have done with https://krustlet.dev and the future pathways that particular  project open up (something along the lines of running a WASM based container in your browser) are particularly interesting.

Reaqtor absolutely isn't a DBMS, but some of the things you mention do resonate with some of the libraries that make up Reaqtor. Expression Trees (ET) are the secret sauce that power LINQ (and Reaqtor). when you write a LINQ statement, that's converted into an ET, and that ET is then converted to whatever the target language / protocol is (you may have heard about [LINQ to Everything](https://www.infoq.com/presentations/LINQ-to-Everything/), another initiative that Bart was involved with). Creating a LINQ Provider is no easy task, the LINQ to Everything project was supposed to make it simpler, and it did produce a number of good examples such as [LINQ to WMI](https://social.msdn.microsoft.com/Forums/en-US/d459291a-4245-45ba-8888-35e07f7cf5b2/rx-sample-of-qbservable-provider-for-wmi-events-linq-to-wql?forum=rx). 

In Reaqtor you write your query, this gets converted into an ET, this is serialized via the Bonsai format, sent over the wire, and then reverse happens. and now on the server you have a stateful, durable Rx subscription running; and this can run for seconds, hours, days, months, on in some cases (in production) years. This is not a DBMS, but these queries tend to evaluate an event stream, but this can either be live (i.e. from something like Azure Event Hubs) or it can be historic (like a capture of IoT sensor telemetry saved to a file system in binary or parquet format). One of the exciting differences is, unlike your example, we don't need to ship POCO objects in a nuget package - Reaqtor has the concept of structural typing, so it can infer the shape of the data and create a synthetic .NET type to represent it. You can, of course supply your own .NET primitives if you like, but that's not a pre-requisite. We actually have a little endjin "show & tell" video where @idg10 explains this process, you can find this here: https://vimeo.com/551539802/952b3bb135

I'm not sure a native LINQ DBMS is likely to happen, if you look at innovations like Cosmos DB, it's a multi-model database as a service which can expose different database personalities (graph, table, key value), and each of those has a different API protocol. Some of the behaviours you desire sound much more like the programming models in the big data space, like Spark, whereby you write your jobs in Python and these are run as jobs across the cluster. There are initiatives like [.NET for Spark](https://dotnet.microsoft.com/apps/data/spark) (I believe this is also part of Jeremy Likness' team), but even this is a set of language bindings from C# to the underlying native Spark APIs. I believe there are valuable utilities in the Nuqleon.* libraries in Reaqtor that could be beneficial in this scenario and have reached out to the team.

There are a couple of .NET Interactive notebooks in the repo that explore the Nuqleon Expression Tree subsystem - you can find [one here](https://github.com/reaqtive/reaqtor/blob/main/Nuqleon/Core/LINQ/Nuqleon.Linq.Expressions.Bonsai/GettingStarted.ipynb) - it might help you understand what's happening under the covers.

**Comment by sam-wheat** [comment]
Hi Howard,  thank you very much for your response.  

With regard to Blazor, I mention it because it demonstrates that many developers (myself included) will willingly take a dependency on a Microsoft-only technology in order to achieve some objective - in this case a unified application model and statically typed code.  Some have responded to my proposal for a LINQ DBMS with "...but it's Microsoft-only..." to which I respond "It does not have to be but if it is, why is that a bad thing?".


Your paragraph that begins with "I'm not sure a native LINQ DBMS is likely to happen" is spot on.  These are the three points I took away from it:

* Products like Cosmos DB and Spark move closer to unifying the database with the application programming language.  

* None have solved the impedance mismatch problem.

* Technologies such as Nuqleon and Reaqtor contain utilities which might be useful in solving the impedance mismatch problem (I presume you are referring to stateful subscriptions, observables, expression tree handling, etc.).

Perhaps you can sense my frustration as the evolution of products such as Cosmos and Spark seems to slowly circle the impedance mismatch problem, never addressing it head on.  Meanwhile truly innovative technologies such as Reaqtor appear to sit idle and unused to that end.  

Your statement "I'm not sure a native LINQ DBMS is likely to happen" is perhaps true.  But it forces us to address other questions: Will we ever solve the impedance mismatch problem?  How will we do it?  Are tools like Entity Framework the best we can do?  Can we leverage tools like Reaqtor and it's components to move closer to a solution?

Please allow me to retract the requests I made in my original post.  The way I should have approached the problem is to state the objective and let you tell me how it should be done:

As a line-of-business application developer I want to extend my application programming model to my DBMS.  I want to be able to write strongly typed queries that may not translate to some query language that is supported natively by the DBMS.  For example `....Where(x => MyMethod(x))`.  I don't care if the solution to this problem is Microsoft-only.  I will gladly make that concession to achieve these goals.  Are tools like Entity Framework the best I can ever hope for?  Can I leverage tools like Reaqtor and it's components to achieve these goals?
