### ISSUE TITLE
Bonsai.Serialization notebook getting started broken

### ISSUE THREAD

**Issue by sommmen** [reaqtive/reaqtor#133]
Hiya, 

https://github.com/reaqtive/reaqtor/blob/main/Nuqleon/Core/LINQ/Nuqleon.Linq.Expressions.Bonsai.Serialization/GettingStarted.ipynb

Seems to be broken;

![image](https://user-images.githubusercontent.com/8641495/223679170-9e74e206-d80b-4af6-8251-9e1e6190b1a2.png)

**Comment by HowardvanRooijen** [comment]
Loads fine for me in Visual Studio Code.

**Comment by sommmen** [comment]
> Contributor
> ###

Apologies, first time using this type of thing.

I installed it in vscode from info on the web and got it running.

Maybe add some links in the docs to open the notebook quickly?
Like https://github.com/dotnet/csharp-notebooks does.

I.e.
vscode://ms-dotnettools.dotnet-interactive-vscode/openNotebook?url=https://raw.githubusercontent.com/reaqtive/reaqtor/main/Nuqleon/Core/LINQ/Nuqleon.Linq.Expressions.Bonsai.Serialization/GettingStarted.ipynb

**Comment by HowardvanRooijen** [comment]
No need to apologise! We're really hoping we can get interactive examples in the readme's soon!
