### ISSUE TITLE
Operator: ElementAt

### ISSUE THREAD

**Issue by carmeleve** [reaqtive/reaqtor#66]
[Link to Rx.NET implementation](https://github.com/dotnet/reactive/blob/main/AsyncRx.NET/System.Reactive.Async.Linq/System/Reactive/Linq/Operators/ElementAt.cs)

**Comment by ronnygunawan** [comment]
Related operator: `ElementAtOrDefault`
[Link to Rx.NET implementation](https://github.com/dotnet/reactive/blob/main/AsyncRx.NET/System.Reactive.Async.Linq/System/Reactive/Linq/Operators/ElementAtOrDefault.cs)
